### ISSUE TITLE
`updateUI()` and `updateErrorUI()` don't block other handlers; should they?

### ISSUE THREAD

**Issue by nonsensery** [Electrode-iOS/ELWebService#38]
The methods `updateUI()` and `updateErrorUI()` allow handlers to be added that run on the main thread. This is really nice. The current implementation does not block the task's operation queue while the UI update code runs, which allows other operations to run simultaneously. This is not so nice.

For example, consider this code:

```
class Brewer {
    var name: String
}

service.GET("/brewer/\(id)")
    .response { data, _ in
        let brewer: Brewer = // decode data…
        return .Value(brewer)
    }
    .updateUI { value in
        let brewer = value as! Brewer
        self.label.text = brewer.name // <-- read
    }
    .transform { value in
        let brewer = value as! Brewer
        brewer.name = "uh oh" // <-- write
    }
```

This is a contrived example, but the point is that this code is **not** thread safe. The `Brewer` instance might be read from the main thread (in the `updateUI()` handler) while it is simultaneously being mutated from a background thread (in the `transform()` handler). It seems reasonable to expect _all_ handlers to be called sequentially.

**Comment by nonsensery** [comment]
P.S. I think switching from `dispatch_async()` to `dispatch_sync()` when running the main thread closures would "fix" this issue.

**Comment by angelodipaolo** [comment]
While I do agree it is totally reasonable to expect that all handlers will execute sequentially I can't think of any case where it would make sense to have a processing handler like `response()` or `transform()` added after `updateUI()`. Does this case come up often in your code?

The `updateUI()` API was intended to be used as the last part of your handler chain. After the response has been processed into a possible meaningful model value, the `updateUI()` handler serves as a convenient way to update your UI with your model data on the main queue. This pattern was borrowed from [SDWebService](https://github.com/walmartlabs-wmusiphone/ios-shared/blob/master/Source/WebServices/SDWebService.h#L154-L157).

I'm a bit hesitant to throw a `dispatch_sync` call in there but it looks like it would "fix" the API weirdness.

Unless there are valid use cases for chaining on handlers after `updateUI()`, I would rather change the API so that after `updateUI()` is called only lifecycle methods like `resume()`, `cancel()`, and `suspend()` can be called. This would allow the API to enforce the intended usage and could be implemented by wrapping `updateUI()`'s return value in a protocol that only exposes the lifecycle methods.

**Comment by nonsensery** [comment]
Here's the case I encountered: I was trying to interact with a custom [API Client](https://github.com/Electrode-iOS/ELWebService/blob/master/docs/Programming-Guide.md#building-an-api-client) that was internally (ab)using `updateUI()` to do some Core Data stuff on the main thread (which is a separate issue). That method looked like:

```swift
class BeerService {
    func fectchBrewer(id) -> ServiceTask {
        return service.GET("/brewer/\(id)")
            .responseJSON { data in
                /* parse data */
                return .Value(brewer)
            }
            .updateUI { brewer in
                /* stash the brewer in Core Data as a local cache */
            }
    }
}
```

My concern was that, since the `ServiceTask` leaks out of `fetchBrewer()`, it could be dangerous for the internal `updateUI()` handler to run asynchronously.

I like the idea of a separate API for late-stage interaction with the task. It reminds me of the [difference between Deferred and Promise on the web](http://stackoverflow.com/questions/6801283/what-are-the-differences-between-deferred-promise-and-future-in-javascript). In this example, it would make sense for some of the `ServiceTask` methods (like `response`) to only be available within `fetchBrewer()`.

**Comment by angelodipaolo** [comment]
After spending more time thinking on this, I think it would be better to be consistent and change `updateUI()` and `updateErrorUI()` to block so that all handers are executed sequentially.
